### PR TITLE
Updated check, fibers

### PR DESCRIPTION
**Pull request by juho**
Updated check from the Meteor repo, fibers to 2.0.0.

### CODE REVIEW

**Comment by raix** [comment]
seems like you have node_modules pushed to git?

**Comment by raix** [comment]
gosh, sorry about that - this package is getting out of memory, just saw node_modules are actually checked in - we might want to handle this differently

**Comment by juho** [comment]
Yeah seemed to be in the base branch. I've only tested this with one project so might wanna give it a go yourself too :)

**Comment by juho** [comment]
@raix You wanna pull this in, then remove node_modules after? Probably easiest

**Pull request merged**
